version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'chore'
    groups:
      development:
        dependency-type: 'development'
      production:
        dependency-type: 'production'
